<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
    'WP_Update_Migrate' => $vendorDir . '/froger-me/wp-update-migrate/class-wp-update-migrate.php',
);
