<?php return array(
    'root' => array(
        'name' => 'froger-me/wp-packages-update-server',
        'pretty_version' => '2.0',
        'version' => '2.0.0.0',
        'reference' => null,
        'type' => 'library',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        'froger-me/wp-packages-update-server' => array(
            'pretty_version' => '2.0',
            'version' => '2.0.0.0',
            'reference' => null,
            'type' => 'library',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'froger-me/wp-update-migrate' => array(
            'pretty_version' => '1.5',
            'version' => '1.5.0.0',
            'reference' => 'master',
            'type' => 'library',
            'install_path' => __DIR__ . '/../froger-me/wp-update-migrate',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'woocommerce/action-scheduler' => array(
            'pretty_version' => '3.8.1',
            'version' => '3.8.1.0',
            'reference' => 'e331b534d7de10402d7545a0de50177b874c0779',
            'type' => 'wordpress-plugin',
            'install_path' => __DIR__ . '/../woocommerce/action-scheduler',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'yahnis-elsts/plugin-update-checker' => array(
            'pretty_version' => 'v5.4',
            'version' => '5.4.0.0',
            'reference' => 'e8e53e6d98e37fa7c895c93417f52e3775494715',
            'type' => 'library',
            'install_path' => __DIR__ . '/../yahnis-elsts/plugin-update-checker',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'yahnis-elsts/wp-update-server' => array(
            'pretty_version' => 'v2.0.1',
            'version' => '2.0.1.0',
            'reference' => '9d44338b13214194121179932a290de3066c5f87',
            'type' => 'library',
            'install_path' => __DIR__ . '/../yahnis-elsts/wp-update-server',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
